SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_INVULNERABILITY_SECONDS = 2.0
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Difficulty ramps linearly from the "start" values toward the "end"
# values over DIFFICULTY_RAMP_SECONDS of survival time, then holds.
DIFFICULTY_RAMP_SECONDS = 120
ASTEROID_SPAWN_RATE_MIN_SECONDS = 0.25
ASTEROID_SPEED_RANGE_START = (40, 100)
ASTEROID_SPEED_RANGE_END = (90, 220)
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN_SECONDS = 0.3

# Smaller asteroids are harder to hit, so they're worth more.
ASTEROID_SCORE_BY_KIND = {1: 100, 2: 50, 3: 20}